#!/usr/bin/env node
/**
 * Generates src/data/qr-matrix.ts — the QR module grid for the footer
 * "© 2026" easter egg (a scannable code that opens the site).
 *
 * Error-correction level H (30% recovery) is deliberate: the data modules
 * are rendered as little fish shapes rather than solid squares, which costs
 * some readability, and the high EC level buys it back.
 *
 * Re-run if SITE_URL changes:  node scripts/gen-qr.mjs
 */
import QR from "qrcode";
import fs from "fs";

const SITE_URL = "https://mlentdesign.github.io/font-pond/";

const qr = QR.create(SITE_URL, { errorCorrectionLevel: "H" });
const size = qr.modules.size;
const data = qr.modules.data; // row-major Uint8Array, 1 = dark

const rows = [];
for (let r = 0; r < size; r++) {
  let s = "";
  for (let c = 0; c < size; c++) s += data[r * size + c] ? "1" : "0";
  rows.push(s);
}

const ts = `// AUTO-GENERATED by scripts/gen-qr.mjs — do not edit by hand.
// QR code for the footer "© 2026" easter egg. Error-correction level H
// (30% recovery) keeps it scannable even though the modules render as fish.
export const QR_URL = ${JSON.stringify(SITE_URL)};
export const QR_SIZE = ${size};
// One string per row; "1" = dark module, "0" = light.
export const QR_MATRIX: readonly string[] = [
${rows.map((r) => `  ${JSON.stringify(r)},`).join("\n")}
];
`;

fs.writeFileSync("src/data/qr-matrix.ts", ts);
console.log(`Wrote src/data/qr-matrix.ts — ${size}×${size} (version ${qr.version})`);
